// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/victoraldir/cutcast/internal/app/record/usecases (interfaces: TrimRecordGroupUseCase)

// Package usecases is a generated GoMock package.
package usecases

import (
	reflect "reflect"

	usecases "github.com/victoraldir/cutcast/internal/app/record/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockTrimRecordGroupUseCase is a mock of TrimRecordGroupUseCase interface.
type MockTrimRecordGroupUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTrimRecordGroupUseCaseMockRecorder
}

// MockTrimRecordGroupUseCaseMockRecorder is the mock recorder for MockTrimRecordGroupUseCase.
type MockTrimRecordGroupUseCaseMockRecorder struct {
	mock *MockTrimRecordGroupUseCase
}

// NewMockTrimRecordGroupUseCase creates a new mock instance.
func NewMockTrimRecordGroupUseCase(ctrl *gomock.Controller) *MockTrimRecordGroupUseCase {
	mock := &MockTrimRecordGroupUseCase{ctrl: ctrl}
	mock.recorder = &MockTrimRecordGroupUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrimRecordGroupUseCase) EXPECT() *MockTrimRecordGroupUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTrimRecordGroupUseCase) Execute(arg0 usecases.TrimRecordGroupCommand) (*usecases.TrimRecordGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(*usecases.TrimRecordGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTrimRecordGroupUseCaseMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTrimRecordGroupUseCase)(nil).Execute), arg0)
}
