# Create workflow file to test, build and deploy image to Docker Hub only when tag is pushed
# Language Go version 1.20.6

name: Go

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test with Go
      run: go test -v
    - name: Build
      run: go build -v
    - name: Docker build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cutcast:$IMAGE_TAG
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cutcast
